### ISSUE TITLE
Inline elements in headings do not inherit parent fontSize

### ISSUE THREAD

**Issue by fvsch** [archriss/react-native-render-html#119]
### Is this a bug report or a feature request?

Bug report.

### Have you read [the guidelines](https://github.com/archriss/react-native-render-html/blob/master/CONTRIBUTING.md) regarding bug report?

Yup.

### Have you read [the documentation](https://github.com/archriss/react-native-render-html/blob/master/README.md) in its entirety?

Yup.

### Have you made sure that your issue hasn't already been reported/solved?

Not seeing it in the latest commits or PRs.

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Yes, seen on both iOS and Android.

### Is the bug reproductible in a production environment (not a debug one)?

Sorry, haven’t tried in a prod build.

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-render-html/tree/master/Demo)?

The demo snippets don’t have this use case.

### Environment

React: 16.0.0
React native: 0.51
react-native-render-html: 3.9.0

### Steps to Reproduce

Render this HTML content:

```js
render() {
  const html = `
    <h1>This is a H1</h1>
    <h1><strong>This</strong> <em>one</em> is <span>great</span> too!</h1>
  `
  return (
    <View>
      <HTML html={html} />
      <View style={{borderTopWidth:1}} />
      <HTML html={html} baseFontStyle={{fontSize:16}} />
      <View style={{borderTopWidth:1}} />
      <HTML html={html} baseFontStyle={{}} />
      <View style={{borderTopWidth:1}} />
      <HTML html={html} tagsStyles={{h1:{fontSize:10}}} />
    </View>
  )
}
```

### Expected Behavior

The inline elements (STRONG, SPAN, EM…) should inherit the fontSize of the parent H1 element.

### Actual Behavior

![Screen shot](https://user-images.githubusercontent.com/243601/37348939-8c30c2fe-26d5-11e8-8ded-f4c1dab3941c.png)

The inline elements are displayed using the `14` font size, unless we specify an empty object for the `baseFontStyle` prop.

### Source of the issue

In HTML.js, `filterBaseFontStyles` is called for each node, including text nodes. We have a structure like this:

```
h1
    strong
        #text
```

The `fontSize: 14` seems to be returned for the text node (not for the STRONG element node).

One bug seems located here:

```js
const tagToCheck = tagName === 'rawtext' ? parentTag : tagName;
...
const overridenFromTagStyle = tagToCheck && tagsStyles[tagToCheck] && tagsStyles[tagToCheck][styleAttribute];
const overridenFromParentTagStyle = parentTag && tagsStyles[parentTag] && tagsStyles[parentTag][styleAttribute];
```

For a text node, `overridenFromTagStyle` and `overridenFromParentTagStyle` will be the same check. This means for our STRONG element's text node, we never check the H1 styles.

But I’m not sure that’s 100% of the issue.

**Comment by fvsch** [comment]
Okay, things are getting even weirder.

Test case:

```js
<HTML
  html={`
  <h1>This is a H1</h1>
  <h1>This <span>is</span> a H1</h1>
  <p>And a paragraph</p>
`}
  tagsStyles={{
    h1: { fontSize: 20 },
    p: { fontSize: 10, color: 'red' }
  }}
/>
```

It looks like if a title has element children, then a Text element is inserted with the styles from `tagStyles.p`. Result is:

![screenshot showing the second H1 using styles defined for P elements](https://user-images.githubusercontent.com/243601/37360329-31271672-26f0-11e8-8b0d-cb252b08cd1d.png)

**Comment by Exilz** [comment]
Your second example kinda broke my brain for a second 😅 

There actually are a couple of different issues resulting in these bugs

First of all, [this part of the code](https://github.com/archriss/react-native-render-html/blob/master/src/HTML.js#L229-L240) explains why your second `h1` becomes red. The `span` in the middle is flagged as needing a wrapper because `child.parent.name !== 'p'` (the very last condition at line 215.)

=> I think this is the first problem, this should be `TEXT_TAGS_IGNORING_ASSOCIATION.indexOf(child.parent.name) === -1` instead. We should check if the parent is one of `p, h1, h2, h3...` not just `p`.

Changing this results in the following : 
![](https://puu.sh/zNanq/ded084143e.png)
which addresses the first issue.

---

The second part of the problem comes from the logic that wraps text nodes that shouldn't trigger a line break into a single `Text` wrapper. Like in this snippet :

`<em>em text</em><u>underline text</u><s>strike through text</s>`

Right now, the code is adding an additional`<p>` tag to do so... Resulting in the following : 
![](https://puu.sh/zNas4/407da0a3f2.png)

[Here is the line responsible for this](https://github.com/archriss/react-native-render-html/blob/master/src/HTML.js#L237). I don't exactly remember why I chose to use paragraphs as wrappers in the first place, but it had something to do with styling the default text. Which is something that has later been fixed with the `baseFontStyle` prop.

Making sure that a dedicated tag (`rawtext`) is used to wrap those texts let us get rid of the red color being applied to our text elements : 

![](https://puu.sh/zNaxo/0997659d69.png)

---

Now about the actual root of the issue, the style inheritance...

I *think* the problem lies in `tagToCheck`. As you pointed out, in the case of a text node, `overridenFromTagStyle` and `overridenFromParentTagStyle` will be the same check. 

But the problem seems bigger than that. I guess that we shouldn't check the parent of the text node, but the highest text wrapper of this node. Which means, in your example : 

```
h1
    strong
        #text
```

#text should filter `baseFontStyle` styles based on `h1`, not `strong`.

So I wrote a beautifully named helper to do so : 

```javascript
export function getFurthestTextParentTagOnUnmappedNodes (node, tag) {
    if (!node || !node.parent) {
        return tag || undefined;
    }
    if (TEXT_TAGS.indexOf(node.parent.name) !== -1) {
        return getFurthestTextParentTagOnUnmappedNodes(node.parent, node.parent.name);
    } else {
        return tag || undefined;
    }
}
```

=> We can't just check for the wrapper key, since we're working on HTML nodes that haven't been through `mapDOMNodesTORNElements` yet 😢  Hence the need for this helper.

Anywayyyyyy, here's what it looks like with this logic : 

![](https://puu.sh/zNcqk/6b9abc89b5.png)

---

This is tricky because multiple parts of the code are at stake here. Thanks again for the very precise bug reports and for helping this plugin get better.

By the way, I wrote this answer as I was tinkering around with the code as a scratchpad, sorry if I'm not making total sense for each point I'm trying to make.

**Comment by fvsch** [comment]
Thanks for following up. Since I had spent some time in the code trying to get the hang of it and find a fix, your answer made perfect sense to me. :)

**Comment by krrevilla** [comment]
Hi, may I ask how did you apply your helper in the code ?

**Comment by Exilz** [comment]
This has been fixed in `3.10.0` without the need for an additional helper.

**Comment by vasuchawla** [comment]
I am using v5.0.1 and still facing this problem. was this removed?

**Comment by jsamr** [comment]
@vasuchawla This fix required a rearchitectural design.  The foundry release fixes this issue, see #430
